# spec at https://docs.digitalocean.com/products/app-platform/references/app-specification-reference/
name: app-template # change this
region: sfo
databases: # remove this section if not using a database
  - name: db
    engine: PG
    num_nodes: 1
    size: db-s-dev-database
    version: '12'

# remove domains section if not using a service
domains:
  - domain: app-template.crvox.com # change this subdomain
    type: PRIMARY
    zone: crvox.com
# remove services section if not using a service (www server)
services:
  - name: web
    envs:
      - key: 'DEBUG'
        value: 'true'
        scope: RUN_TIME
      - key: 'DATABASE_URL'
        value: 'postgres://${db.USERNAME}:${db.PASSWORD}@${db.HOSTNAME}:${db.PORT}/${db.DATABASE}'
        scope: RUN_TIME
      - key: 'CA_CERT'
        value: '${db.CA_CERT}'
        scope: RUN_TIME
    routes:
      - path: /
    github:
      repo: cryptovoxels/app_template # change this
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm run server
    environment_slug: node-js
    instance_size_slug: basic-xs
    instance_count: 1
    http_port: 8080
    health_check:
      initial_delay_seconds: 10
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 3
      failure_threshold: 5
      http_path: /zhealth
# remove workers if not using background workers
#workers:
#  - github:
#      repo: cryptovoxels/app_template # change this
#      branch: main
#      deploy_on_push: true
#    build_command: npm run build
#    run_command: npm run worker
#    environment_slug: node-js
#    envs:
#      - key: 'DEBUG'
#        value: 'true'
#        scope: RUN_TIME
#      - key: 'DATABASE_URL'
#        value: 'postgres://${db.USERNAME}:${db.PASSWORD}@${db.HOSTNAME}:${db.PORT}/${db.DATABASE}'
#        scope: RUN_TIME
#      - key: 'CA_CERT'
#        value: '${db.CA_CERT}'
#        scope: RUN_TIME
#    instance_count: 1
#    instance_size_slug: basic-xs
#    name: worker
