# spec at https://docs.digitalocean.com/products/app-platform/references/app-specification-reference/
name: nft-modifier # change this
region: sfo

# remove domains section if not using a service
domains:
  - domain: notifier.crvox.com # change this subdomain
    type: PRIMARY
    zone: crvox.com
# remove services section if not using a service (www server)
services:
  - name: web
    envs:
      - key: 'DEBUG'
        value: 'true'
        scope: RUN_TIME
      - key: 'CA_CERT'
        value: '${db.CA_CERT}'
        scope: RUN_TIME
    routes:
      - path: /
    github:
      repo: cryptovoxels/app_template # change this
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm run server
    environment_slug: node-js
    instance_size_slug: basic-xs
    instance_count: 1
    http_port: 8080
    health_check:
      initial_delay_seconds: 10
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 3
      failure_threshold: 5
      http_path: /zhealth
